services:
  rocky9build:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
      - ccache9rocky:/home/centos/.ccache
    build:
      context: .
      args:
        os: $RL9
  rocky9buildreloc:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
      - ccache9rocky:/home/centos/.ccache
    build:
      context: .
      args:
        os: $RL9

volumes:
  rpm9rocky:
    name: rpm9rocky
  ccache9rocky:
    name: ccache9rocky
